import React, { StrictMode } from 'react';
import { hydrateRoot } from 'react-dom/client';
import { createStore } from 'redux';
import { Provider } from 'react-redux';

import rootReducer from '../common/store/reducer';
import App from '../common/components/app';

// Create store, pass initial state (eg: locale, i18n, route) generated by server
const store = createStore(rootReducer, window.__STATE__);

// Mount app to existing DOM
hydrateRoot(
  document.getElementById('editor'),
  <Provider store={ store }>
    <StrictMode>
      <App/>
    </StrictMode>
  </Provider>
);
